website/views.py
from datetime import datetime

from flask import Blueprint, render_template, request, flash, redirect, url_for
from .db import *

views = Blueprint('views', __name__)

# current signed in customer
curr_cus = 1


@views.route('/')
def home():
    # customer = get_customer(12)
    # print(customer)
    return render_template('home.html', customer=get_customer(curr_cus))


@views.route('/new_customer', methods=['GET', 'POST'])
def new_customer():
    global curr_cus
    if request.method == 'POST':
        first = request.form.get('firstName').capitalize()
        middle = request.form.get('middleName').capitalize()
        last = request.form.get('lastName').capitalize()
        email = request.form.get('email')
        address = request.form.get('address')
        gender = request.form.get('gender')
        phone = request.form.get('phone')
        date = request.form.get('b_date')
        date = datetime.strptime(date, "%Y-%m-%d").date()
        plan = request.form.get('plan')

        if date > datetime.today().date():
            flash('Please enter a valid birth date!', 'danger')
            return redirect(url_for('views.new_customer'))

        if not (first and last and middle and address and email and phone and gender):
            flash('Please enter all data!', 'danger')
            return redirect(url_for('views.new_customer'))

        try:
            cus = add_customer(first, middle, last, email, address, date, gender, phone)
            add_contract_customer(cus, plan)
            curr_cus = cus
        except:
            flash('Please enter valid data!', 'danger')
            return redirect(url_for('views.new_customer'))

        flash('User created successfully!', 'success')
        return redirect(url_for('views.customer'))

    return render_template('new_customer.html', plans=get_plans(get_hos_num=True))


@views.route('/new_dependent', methods=['GET', 'POST'])
def new_dependent():
    global curr_cus
    if request.method == 'POST':
        try:
            name = request.form.get('name').capitalize()
            kinship = request.form.get('kinship').capitalize()
            gender = request.form.get('gender')
            date = request.form.get('b_date')
            date = datetime.strptime(date, "%Y-%m-%d").date()
            plan = request.form.get('plan')

            if date > datetime.today().date():
                flash('Please enter a valid birth date!', 'danger')
                return redirect(url_for('views.new_dependent'))

            if not (name and gender and kinship and plan):
                flash('Please enter all data!', 'danger')
                return redirect(url_for('views.new_dependent'))
            try:
                add_dependent(curr_cus, name, date, gender, kinship)
                add_contract_dependent(curr_cus, name, kinship, plan)
                flash('Dependent added successfully!', 'success')
                return redirect(url_for('views.customer'))
            except:
                flash('Dependent already exist!', 'danger')
                return redirect(url_for('views.new_dependent'))

        except:
            ...
    return render_template('new_dependent.html', plans=get_plans(get_hos_num=True))


@views.route('/admin/new_hospital', methods=['POST', 'GET'])
def new_hospital():
    global curr_cus
    plans = get_plans()
    if request.method == 'POST':
        name = request.form.get('name').capitalize()
        email = request.form.get('email')
        address = request.form.get('address')
        phone = request.form.get('phone')

        plans = [request.form.get(i['type']) for i in plans]
        print(plans)
        plans_ids = [int(i) for i in plans if i]

        if not (name and email and address and phone and plans_ids):
            flash('Please enter all data!', 'danger')
            return redirect(url_for('views.new_hospital'))

        try:
            hos = add_hospital(name, address, email, phone)
            enroll_hospital_in_plans(hos, plans_ids)

        except:
            flash('Please enter valid data!', 'danger')
            return redirect(url_for('views.new_hospital'))

        flash('Hospital added successfully!', 'success')
        return redirect(url_for('views.admin'))

    return render_template('new_hospital.html', plans=plans)


@views.route('/customer')
def customer():
    global curr_cus
    return render_template('customer_home.html', cus=get_customer(curr_cus))


@views.route('/customer/file_claim', methods=['POST', 'GET'])
def file_claim():
    global curr_cus
    hospitals = {}
    for i in get_plans():
        hospitals[i['id']] = get_available_hospitals_for_plan(i['id'])
    cus = get_customer(curr_cus, include_cont_plan=True)
    deps = get_customer_dependents(curr_cus, include_cont_plan=True)
    people = [cus] + deps

    if request.method == 'POST':
        try:
            con_id = int(request.form.get('ben'))
            hos_id = int(request.form.get('hos'))
            subject = request.form.get('subject')
            amount = int(request.form.get('amount'))
            details = request.form.get('details')

            if not (con_id and hos_id and subject and amount and details):
                flash('Please enter all data!', 'danger')
                return redirect(url_for('views.file_claim'))

            add_claim(con_id, hos_id, amount, subject, details)
            flash('Claim filed successfully!', 'success')
            return redirect(url_for('views.customer'))
        except:
            flash('Please enter valid data!', 'danger')
            return redirect(url_for('views.file_claim'))

    return render_template('file_claim.html', hospitals=hospitals, people=people, plans=get_plan_id_name_dict())


@views.route('/admin/claims/<cid>', methods=['POST', 'GET'])
def view_claim(cid):
    global curr_cus
    if request.method == 'POST':
        try:
            claim_id = int(request.form.get('claim_id'))
            status = request.form.get('action')
            if status == 'accept':
                flash('Claim is accepted and marked as resolved!', 'success')
            if status == 'deny':
                flash('Claim is denied and marked as resolved!', 'success')

            mark_claim_as_resolved(claim_id, status == 'accept')
            redirect(url_for('views.view_claim', cid=cid))
        except:
            ...
    try:
        claim = get_claim(cid)
        contract = get_contract(claim['con_id'])
        if contract['cus_id']:
            filed = get_customer(contract['cus_id'])
            ben = 'The customer'
        else:
            filed = get_customer(contract['res_id'])
            ben = f'{contract["dep_name"]} ({contract["kinship"]})'
        hospital_name = get_hospital(claim['hos_id'])['name']
        return render_template('view_claim.html', claim=claim, filed=filed, hos=hospital_name, ben=ben)
    except:
        return redirect(url_for('views.home'))


@views.route('/customer/available-hospitals')
def available_hospitals():
    global curr_cus
    hospitals = {}
    for i in get_plans():
        hospitals[i['id']] = get_available_hospitals_for_plan(i['id'])
    cus = get_customer(curr_cus, include_cont_plan=True)
    deps = get_customer_dependents(curr_cus, include_cont_plan=True)
    deps_with_plan = [i for i in deps if i['plan_type']]
    people = [cus] + deps_with_plan

    return render_template('available_hospitals.html', hospitals=hospitals, people=people)


@views.route('/admin')
def admin():
    return render_template('admin.html')


@views.route('/admin/customers')
def view_customers():
    customers = get_all_customers()
    return render_template('view_customers.html', customers=customers)


@views.route('/admin/customers/<id>')
def view_customer(id):
    cus = get_customer(int(id), include_cont_plan=True)
    deps = get_customer_dependents(int(id), include_cont_plan=True)
    if cus:
        return render_template('customer_details.html', cus=cus, deps=deps)
    else:
        flash("Customer doesn't exist", "danger")
        return redirect(url_for('views.customers'))


@views.route('/admin/customers/<id>/claims', methods=['POST', 'GET'])
def view_claims(id):
    unresolved = False
    if request.method == 'GET':
        f = request.args.get('unresolved')
        unresolved = f == '1'
    if unresolved:
        claims = get_unresolved_claims_for_customer(id)

    else:
        claims = get_claims_for_customer(id)

    return render_template('view_claims.html', claims=claims, unresolved=unresolved, customer=get_customer(id))


@views.route('/admin/latest_claims', methods=['POST', 'GET'])
def latest_claims():
    claims = get_latest_claims()
    return render_template('view_claims.html', claims=claims, latest=1)


@views.route('/customer/claims', methods=['POST', 'GET'])
def view_my_claims():
    global curr_cus
    claims = get_claims_for_customer(curr_cus)
    return render_template('view_claims.html', claims=claims, is_cus=1)


@views.route('/customer/claims/<cid>', methods=['POST', 'GET'])
def view_my_claim(cid):
    global curr_cus
    try:
        claim = get_claim(cid)
        contract = get_contract(claim['con_id'])

        if curr_cus not in [contract['cus_id'], contract['res_id']]:
            flash('You are not allowed to see this claim!', 'danger')
            return redirect(url_for('views.view_my_claims'))
        if contract['cus_id']:
            filed = get_customer(contract['cus_id'])
            ben = 'You'
        else:
            filed = get_customer(contract['res_id'])
            ben = f'{contract["dep_name"]} ({contract["kinship"]})'
        hospital_name = get_hospital(claim['hos_id'])['name']
        return render_template('view_claim.html', claim=claim, filed=filed, hos=hospital_name, ben=ben, is_cus=1)
    except:
        flash('claim does not exist!', 'danger')
        return redirect(url_for('views.view_my_claims'))


@views.route('/customer/purchase', methods=['POST', 'GET'])
def purchase():

website/templates/admin.html
{% extends "base.html" %}
{% block title %}Homes{% endblock %}
{% block content %}
<div>
    <div>
        <h4 style="margin-top: 0;padding-top: 40px;padding-left: 103px;color: var(--bs-gray-dark);">Welcome back, Admin.</h4>
        <div class="d-lg-flex justify-content-center"></div>
    </div>
    <div>
        <div class="d-lg-flex justify-content-lg-center"></div>
    </div>
    <div class="d-lg-flex justify-content-center justify-content-lg-center" style="margin-right: 100px;margin-left: 100px;margin-top: 24px;margin-bottom: 50px;">
        <div class="container shadow" style="background: rgba(177,53,220,0.07);padding: 29px;border-radius: 14px;">
            <div class="row">
                <div class="col-md-12">
                    <div class="d-lg-flex justify-content-lg-center" style="text-align: center;"></div>
                </div>
            </div>
            <div class="row" style="margin-top: -17px;padding-top: 51px;padding-bottom: 56px;border-top-color: var(--bs-cyan);">
                <div class="col-md-12 text-center">
                   <button onclick="window.location.href='{{ url_for( 'views.view_customers' ) }}';" class="btn btn-primary border rounded" type="button" style="width: 270px;min-width: 270px;max-width: 270px;margin: 10px 35px;filter: hue-rotate(0deg);height: 78px;font-size: 20px;font-weight: bold;background:#4c2a9f;">
                       <svg class="bi bi-people-fill" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" style="margin-right: 15px;width: 30px;height: 30px;margin-top: -7px;">
                            <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"></path>
                            <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"></path>
                            <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"></path>
                    </svg>View Customers</button>

                   <button onclick="window.location.href='{{ url_for( 'views.new_hospital' ) }}';" class="btn btn-primary border rounded" type="button"style="width: 270px;min-width: 270px;max-width: 270px;margin: 10px 35px;filter: hue-rotate(0deg);height: 78px;font-size: 20px;font-weight: bold;background: #1c2f4c;">
                       <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none" style="margin-right: 15px;width: 30px;height: 30px;margin-top: -6px;">
                            <path d="M12 6C12.5523 6 13 6.44772 13 7V11H17C17.5523 11 18 11.4477 18 12C18 12.5523 17.5523 13 17 13H13V17C13 17.5523 12.5523 18 12 18C11.4477 18 11 17.5523 11 17V13H7C6.44772 13 6 12.5523 6 12C6 11.4477 6.44772 11 7 11H11V7C11 6.44772 11.4477 6 12 6Z" fill="currentColor"></path>
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M5 22C3.34315 22 2 20.6569 2 19V5C2 3.34315 3.34315 2 5 2H19C20.6569 2 22 3.34315 22 5V19C22 20.6569 20.6569 22 19 22H5ZM4 19C4 19.5523 4.44772 20 5 20H19C19.5523 20 20 19.5523 20 19V5C20 4.44772 19.5523 4 19 4H5C4.44772 4 4 4.44772 4 5V19Z" fill="currentColor"></path>
                    </svg>New Hospital</button>

                   <button onclick="window.location.href='{{ url_for( 'views.latest_claims' ) }}';" class="btn btn-primary border rounded" type="button"style="width: 270px;min-width: 270px;max-width: 270px;margin: 10px 35px;filter: hue-rotate(0deg);height: 78px;font-size: 20px;font-weight: bold;background: #510606;">
                       <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none" style="margin-right: 15px;width: 30px;height: 30px;margin-top: -6px;">
                            <path d="M12 6C12.5523 6 13 6.44772 13 7V11H17C17.5523 11 18 11.4477 18 12C18 12.5523 17.5523 13 17 13H13V17C13 17.5523 12.5523 18 12 18C11.4477 18 11 17.5523 11 17V13H7C6.44772 13 6 12.5523 6 12C6 11.4477 6.44772 11 7 11H11V7C11 6.44772 11.4477 6 12 6Z" fill="currentColor"></path>
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M5 22C3.34315 22 2 20.6569 2 19V5C2 3.34315 3.34315 2 5 2H19C20.6569 2 22 3.34315 22 5V19C22 20.6569 20.6569 22 19 22H5ZM4 19C4 19.5523 4.44772 20 5 20H19C19.5523 20 20 19.5523 20 19V5C20 4.44772 19.5523 4 19 4H5C4.44772 4 4 4.44772 4 5V19Z" fill="currentColor"></path>
                    </svg>Latest Claims</button>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/customer_home.html
{% extends "base.html" %}
{% block title %}Homes{% endblock %}
{% block content %}
<div>
    <div>
        <h4 style="margin-top: 0;padding-top: 40px;padding-left: 103px;color: var(--bs-gray-dark);">Welcome back, {{ cus.f_name }}</h4>
        <div class="d-lg-flex justify-content-center"></div>
    </div>
    <div class="d-lg-flex justify-content-center justify-content-lg-" style="margin-right: 100px;margin-left: 100px;margin-top: 24px;margin-bottom: 50px;">
        <div class="container shadow" style="background: rgba(70,211,126,0.18);padding: 29px;border-radius: 14px;">
            <div class="row" style="margin-top: -11px;padding-top: 51px;padding-bottom: 56px;border-top-color: var(--bs-cyan);">
                <div class="col">
                    <div class="row">
                        <div class="col-md-12 text-center">

                            <button onclick="window.location.href='{{ url_for( 'views.file_claim'  ) }}';" class="btn btn-primary border rounded" type="button" style="width: 270px;min-width: 270px;max-width: 270px;margin: 10px 35px;filter: hue-rotate(0deg);height: 78px;font-size: 20px;font-weight: bold;background: var(--bs-green);"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none" style="margin-right: 15px;width: 30px;height: 30px;margin-top: -6px;">
                                    <path d="M12 6C12.5523 6 13 6.44772 13 7V11H17C17.5523 11 18 11.4477 18 12C18 12.5523 17.5523 13 17 13H13V17C13 17.5523 12.5523 18 12 18C11.4477 18 11 17.5523 11 17V13H7C6.44772 13 6 12.5523 6 12C6 11.4477 6.44772 11 7 11H11V7C11 6.44772 11.4477 6 12 6Z" fill="currentColor"></path>
                                    <path fill-rule="evenodd" clip-rule="evenodd" d="M5 22C3.34315 22 2 20.6569 2 19V5C2 3.34315 3.34315 2 5 2H19C20.6569 2 22 3.34315 22 5V19C22 20.6569 20.6569 22 19 22H5ZM4 19C4 19.5523 4.44772 20 5 20H19C19.5523 20 20 19.5523 20 19V5C20 4.44772 19.5523 4 19 4H5C4.44772 4 4 4.44772 4 5V19Z" fill="currentColor"></path>
                                </svg>File New Claim </button>

                            <button onclick="window.location.href='{{ url_for( 'views.available_hospitals'  ) }}';" class="btn btn-primary border rounded" type="button" style="width: 270px;min-width: 270px;max-width: 270px;margin: 10px 35px;height: 78px;font-weight: bold;font-size: 20px;background: #4c2a9f;"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none" style="margin-right: 15px;height: 30px;width: 30px;margin-top: -4px;">
                                    <path fill-rule="evenodd" clip-rule="evenodd" d="M5 5C3.34315 5 2 6.34315 2 8V16C2 17.6569 3.34315 19 5 19H19C20.6569 19 22 17.6569 22 16V8C22 6.34315 20.6569 5 19 5H5ZM7 7H5C4.44772 7 4 7.44772 4 8V9H7V7ZM9 7V9H20V8C20 7.44771 19.5523 7 19 7H9ZM7 11H4V13H7V11ZM9 13V11H20V13H9ZM7 15H4V16C4 16.5523 4.44772 17 5 17H7V15ZM9 17V15H20V16C20 16.5523 19.5523 17 19 17H9Z" fill="currentColor"></path>
                                </svg>Available Hospitals </button>

                            <button onclick="window.location.href='{{ url_for( 'views.new_dependent'  ) }}';" class="btn btn-primary border rounded" type="button" style="background: #791616;width: 270px;min-width: 270px;max-width: 270px;margin: 10px 35px;height: 78px;font-weight: bold;font-size: 20px;"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none" style="margin-right: 15px;height: 30px;width: 30px;margin-top: -10px;">
                                    <path fill-rule="evenodd" clip-rule="evenodd" d="M16 9C16 11.2091 14.2091 13 12 13C9.79086 13 8 11.2091 8 9C8 6.79086 9.79086 5 12 5C14.2091 5 16 6.79086 16 9ZM14 9C14 10.1046 13.1046 11 12 11C10.8954 11 10 10.1046 10 9C10 7.89543 10.8954 7 12 7C13.1046 7 14 7.89543 14 9Z" fill="currentColor"></path>
                                    <path fill-rule="evenodd" clip-rule="evenodd" d="M12 1C5.92487 1 1 5.92487 1 12C1 18.0751 5.92487 23 12 23C18.0751 23 23 18.0751 23 12C23 5.92487 18.0751 1 12 1ZM3 12C3 14.0902 3.71255 16.014 4.90798 17.5417C6.55245 15.3889 9.14627 14 12.0645 14C14.9448 14 17.5092 15.3531 19.1565 17.4583C20.313 15.9443 21 14.0524 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12ZM12 21C9.84977 21 7.87565 20.2459 6.32767 18.9878C7.59352 17.1812 9.69106 16 12.0645 16C14.4084 16 16.4833 17.1521 17.7538 18.9209C16.1939 20.2191 14.1881 21 12 21Z" fill="currentColor"></path>
                                </svg>Add Dependent </button>

                            <button onclick="window.location.href='{{ url_for( 'views.view_my_claims'  ) }}';" class="btn btn-primary border rounded" type="button" style="width: 270px;min-width: 270px;max-width: 270px;margin: 10px 35px;height: 78px;font-weight: bold;font-size: 20px;background:#1c2f4c;"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none" style="margin-right: 15px;height: 30px;width: 30px;margin-top: -4px;">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M3 5C3 3.34315 4.34315 2 6 2H14C17.866 2 21 5.13401 21 9V19C21 20.6569 19.6569 22 18 22H6C4.34315 22 3 20.6569 3 19V5ZM13 4H6C5.44772 4 5 4.44772 5 5V19C5 19.5523 5.44772 20 6 20H18C18.5523 20 19 19.5523 19 19V9H13V4ZM18.584 7C17.9413 5.52906 16.6113 4.4271 15 4.10002V7H18.584Z" fill="currentColor"></path>
                            </svg>My Claims </button>

                            <button onclick="window.location.href='{{ url_for( 'views.purchase'  ) }}';" class="btn btn-primary border rounded" type="button" style="width: 270px;min-width: 270px;max-width: 270px;margin: 20px 35px;height: 78px;font-weight: bold;font-size: 20px;background:#093e4e;"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none" style="margin-right: 15px;height: 30px;width: 30px;margin-top: -10px;">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M11 19V22H13V19H14C16.2091 19 18 17.2091 18 15C18 12.7909 16.2091 11 14 11H13V7H15V9H17V5H13V2H11V5H10C7.79086 5 6 6.79086 6 9C6 11.2091 7.79086 13 10 13H11V17H9V15H7V19H11ZM13 17H14C15.1046 17 16 16.1046 16 15C16 13.8954 15.1046 13 14 13H13V17ZM11 11V7H10C8.89543 7 8 7.89543 8 9C8 10.1046 8.89543 11 10 11H11Z" fill="currentColor"></path>
                            </svg>Purchase Plan </button>

</div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/view_claims.html
{% if is_cus %}
    {% set sub_cus = true %}
{% else %}
    {% set sub_admin = true %}
{% endif %}

{% extends "base.html" %}
{% block title %}Homes{% endblock %}
{% block content %}
    <div>
    <div>
        <div>
            <div class="d-lg-flex justify-content-lg-center"></div>
        </div>
        <div class="d-lg-flex justify-content-center justify-content-lg-center" style="margin-right: 100px;margin-left: 100px;margin-top: 24px;margin-bottom: 50px;">
            <div class="container shadow" style="background: rgba(70,211,126,0.18);padding: 29px;border-radius: 14px;">
                <div>
                    <div class="row" style="margin-top: -17px;padding-top: 51px;padding-bottom: -8px;border-top-color: var(--bs-cyan);">
                        <div class="col">
                            <div class="row">
                                <div class="col-md-12 text-center">
                                {% if not is_cus and not latest %}
                                    <h6 class="text-center" style="background: var(--bs-yellow);padding: 9px 9px 13px;margin-bottom: 18px;color: var(--bs-indigo);font-size: 18px;">{% if not unresolved %}All{% else %}Unresolved{% endif %} claims filed by {{ customer.f_name + ' ' + customer.l_name }}</h6>
                                {% elif latest %}
                                    <h6 class="text-center" style="background: var(--bs-yellow);padding: 9px 9px 13px;margin-bottom: 18px;color: var(--bs-indigo);font-size: 18px;">Latest filed claims</h6>
                                {% else %}
                                    <h6 class="text-center" style="background: var(--bs-yellow);padding: 9px 9px 13px;margin-bottom: 18px;color: var(--bs-indigo);font-size: 18px;">Your Claims</h6>
                                {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <br>
            <br>

            {% if claims|length == 0 %}
                {% if is_cus %}
                    <div style="text-align:center"><h4>You have no claims.</h4></div>
                {% elif unresolved %}
                    <div style="text-align:center"><h4>No unresolved claims for this user.</h4></div>
                {% elif latest %}
                    <div style="text-align:center"><h4>No Latest claims are available.</h4></div>
                {% else %}
                    <div style="text-align:center"><h4>Customer didn't file any claims.</h4></div>
                {% endif %}

            {% else %}

            <div class="d-flex d-sm-flex d-md-flex d-lg-flex d-xl-flex d-xxl-flex justify-content-center">
                <div class="row" style="width: 938.6px;">
                    <div class="col d-lg-flex align-items-lg-center" style="width: 20%;min-width: 499px;">
                        <p style="font-weight: bold; font-size:19px; text-align: left;width: 30%;">Subject</p>
                        <p style="font-weight: bold; font-size:19px; text-align: left;width: 30%;">Filed Date</p>
                        <p style="font-weight: bold; font-size:19px; text-align: left;width: 30%;">Status</p>
                        <p style="min-width: 93px;max-width: 93px;"></p>
                    </div>
                </div>
            </div>

            {% endif %}

            {% for claim in claims %}
                <div class="d-flex d-sm-flex d-md-flex d-lg-flex d-xl-flex d-xxl-flex justify-content-center">
                    <ul class="list-group" style="width: 938.6px;">
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col d-lg-flex align-items-lg-center" style="width: 20%;min-width: 499px;">

                                    <p style="font-size:19px; text-align: left;width: 40%;">{{ claim.expenses_subject }}</p>
                                    <p style="font-size:19px; text-align: left;width: 40%;">{{ claim.f_date }}</p>
                                                {% if not claim.is_resolved %}
                                                    <p style="width: 20%;">Not resolved</p>
                                                {% elif claim.status %}
                                                    <p style="width: 20%;color:darkblue; ">Accepted</p>
                                                {% else %}
                                                    <p style="width: 20%;color: red ;">Denied</p>
                                                {% endif %}
                                </div>
                                {% if is_cus %}
                                    <div class="col text-end" style="min-width: 218px;max-width: 218px;"><button onclick="window.location.href='{{ url_for( 'views.view_my_claim' , cid=claim.id ) }}';" class="btn btn-primary" type="button" style="margin-right: 6px;font-size: 14px;">More Details</button></div>
                                {% else %}
                                    <div class="col text-end" style="min-width: 218px;max-width: 218px;"><button onclick="window.location.href='{{ url_for( 'views.view_claim' , cid=claim.id ) }}';" class="btn btn-primary" type="button" style="margin-right: 6px;font-size: 14px;">More Details</button></div>
                                {% endif %}
                            </div>
                        </li>
                    </ul>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

website/templates/view_customers.html
{% set sub_admin = true %}

{% extends "base.html" %}
{% block title %}Homes{% endblock %}
{% block content %}
    <div>
        <div>
            <div>
                <div class="d-lg-flex justify-content-lg-center"></div>
            </div>
            <div class="d-lg-flex justify-content-center justify-content-lg-center" style="margin-right: 100px;margin-left: 100px;margin-top: 24px;margin-bottom: 50px;">
                <div class="container shadow" style="background: rgba(70,211,126,0.18);padding: 29px;border-radius: 14px;">
                    <div>
                        <div class="row" style="margin-top: -17px;padding-top: 51px;padding-bottom: -8px;border-top-color: var(--bs-cyan);">
                            <div class="col">
                                <div class="row">
                                    <div class="col-md-12 text-center">
                                        <h2 class="text-center" style="background:var(--bs-yellow);padding: 9px 9px 13px;margin-bottom: 18px;color: var(--bs-indigo);font-size: 27px;font-weight: bold;">Customers</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <br>
                <br>
                <br>
                    <div class="d-flex d-sm-flex d-md-flex d-lg-flex d-xl-flex d-xxl-flex justify-content-center">
                        <ul class="list-group" style="width: 738.6px;">
                            {% for cus in customers %}
                            <li class="list-group-item">
                                <div class="row">
                                    <div class="col d-lg-flex align-items-lg-center" style="width: 375.8px;min-width: 499px;">
                                        <h5 style="text-align: left;width: 455.6px;">{{ cus.f_name.capitalize() }} {{ cus.m_name }} {{ cus.l_name }} </h5>
                                    </div>
                                    <div class="col text-end" style="min-width: 218px;max-width: 218px;"><button onclick="window.location.href='{{ url_for( 'views.view_customer', id=cus.id  ) }}';"  class="btn btn-primary" type="button" style="margin-right: 6px;">Customer Details</button></div>
                                </div>
                            </li>
                            {% endfor %}
                        <br><br><br><br>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}